Repository bhp-lims/bhp.lims, pull requests merged in 2019-03, with the labels that each got.

#207 Allow the labman to manually set the Assay Date
  bhp/lims/adapters/__init__.py
  bhp/lims/adapters/configure.zcml
  bhp/lims/adapters/widgetvisibility.py
  bhp/lims/configure.zcml
  bhp/lims/content/analysisrequest.py
Labels: Enhancement

#208 Display analysis remarks in results reports
  bhp/lims/impress/reports/awesome.pt
Labels: Enhancement

#206 Adding pid in subject email
  bhp/lims/impress/emailview.py
Labels: Issue done

#205 adding visit code field
  bhp/lims/browser/templates/delivery.pt
  bhp/lims/config.py
  bhp/lims/content/analysisrequest.py
  bhp/lims/setuphandlers.py
Labels: Issue done

#212 Grading of results functionality
  bhp/lims/api.py
  bhp/lims/browser/analysisspecification.py
  bhp/lims/browser/widgets/analysisspecificationwidget.py
  bhp/lims/config.py
  bhp/lims/content/analysisspec.py
  bhp/lims/impress/reports/awesome.pt
  bhp/lims/impress/reportview.py
  bhp/lims/monkeys/browser/analyses.py
  bhp/lims/resources/results_ranges.xlsx
  bhp/lims/setuphandlers.py
  bhp/lims/skins/bhp_css/main.css
  bhp/lims/specscalculations.py
Labels: Addition, Enhancement, P1: Urgent

#213 Fix Traceback on Sample invalidation
  bhp/lims/monkeys/idserver.py
  bhp/lims/setuphandlers.py
Labels: Bug, P0: Critical

#215 Adding other choices visit code field
  bhp/lims/config.py
Labels: P0: Critical, P1: Urgent
