Repository bhp-lims/bhp.lims, pull requests merged in 2019-04, with the labels that each got.

#224 Add client sample id in requisition form
  CHANGES.rst
  bhp/lims/browser/templates/requisition.pt
Labels: Addition, Issue done, P1: Urgent

#225 Allow dropdown menu for volume units when creating an analysis request
  CHANGES.rst
  bhp/lims/api.py
  bhp/lims/browser/widgets/volumeunitwidget.py
  bhp/lims/config.py
  bhp/lims/content/analysisrequest.py
  bhp/lims/fields.py
  bhp/lims/monkeys/browser/analysisrequest/add2.py
  bhp/lims/monkeys/configure.zcml
  bhp/lims/profiles/default/skins.xml
  bhp/lims/skins/bhp_widgets/volumeunit.pt
Labels: Enhancement

#227 Make the exporter to be client/context-aware
  bhp/lims/export.py
Labels: Enhancement

#228 Delivery checklist should have a container type
  CHANGES.rst
  bhp/lims/browser/templates/delivery.pt
  src/__init__.py
Labels: Enhancement, P0: Critical, P1: Urgent, P2: Very Important
